name: Update idapython_plugins with IDA Pro Python Plugins

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-idapython-plugins:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Search for Python plugin repositories
        id: search
        run: |
          # 1. 将 --limit 提高到 1000
          # 2. 简化 jq 过滤器，直接使用 .repository.fullName
          gh search code '"def PLUGIN_ENTRY()" language:Python' --limit 100 --json repository --jq '[.[] | .repository.fullName] | unique | .[]' > repos_python.txt

          # 增加一个调试输出，方便观察结果
          echo "Found $(wc -l < repos_python.txt) unique Python plugin repositories. See list below:"
          cat repos_python.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 后续的 "Update idapython_plugins.md" 和 "Commit and push" 步骤保持不变
      - name: Update idapython_plugins.md with Python plugin list
        run: |
          python -c "
          import re
          with open('repos_python.txt', 'r') as f:
              repos = [line.strip() for line in f.readlines() if line.strip()]
          markdown_list = []
          for repo in repos:
              markdown_list.append(f'- [{repo}](https://github.com/{repo})')
          list_content = '\n'.join(markdown_list)
          new_content = f'<!-- IDA_PYTHON_PLUGINS_START -->\n{list_content}\n<!-- IDA_PYTHON_PLUGINS_END -->'
          with open('idapython_plugins.md', 'r') as f:
              idapython_plugins_content = f.read()
          updated_idapython_plugins = re.sub(
              r'<!-- IDA_PYTHON_PLUGINS_START -->(.|\n)*<!-- IDA_PYTHON_PLUGINS_END -->',
              new_content,
              idapython_plugins_content
          )
          with open('idapython_plugins.md', 'w') as f:
              f.write(updated_idapython_plugins)
          "
      - name: Commit and push if changed
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          if ! git diff --quiet idapython_plugins.md; then
            git add idapython_plugins.md
            git commit -m "docs: update Python plugin list"
            git push
            echo "idapython_plugins.md updated for Python plugins."
          else
            echo "No changes for Python plugins."
          fi
